# USED IN LOCAL START UP
server:
  port: 3000
  read_timeout: 15
  write_timeout: 15

jwt:
  expires: "20s"

logger:
  error_file: errors.log
  log_file: logs.log

cache:
  type: redis
  url: localhost:6379
  password: "local"
  username: "local"

datastore:
  type: POSTGRES
  name: testsho
  username: "zaffere"
  password: ""
  host: localhost
  port: 5432
  ssl: disable
  max_connection: 10

# 💡TODO: Implement in config
random_user_service:
  client_type: HTTP
  base_url: https://randomuser.me/
  path: /api
  timeout: 1000
  headers:
    accept: application/json
