server:
  port: 3000
  read_timeout: 15
  write_timeout: 15

logger:
  error_file: errors.log
  log_file: logs.log

cache:
  type: redis
  url: localhost:6379
  password:
  username:

datastore:
  name: showwdb
  username: "postgres"
  password: "postgres"
  host: postgres
  port: 5432
  ssl: disable
  max_connection: 50

random_user_service:
  client_type: HTTP
  base_url: https://randomuser.me/
  path: /api
  timeout: 1000
  headers:
    accept: application/json
