# USED IN DOCKER START UP
server:
  port: 3000
  read_timeout: 15
  write_timeout: 15

jwt:
  expires: "20s"
  secret: q*{g!WJ$2MYa7&sK9Z56_8h+d-pTL

logger:
  error_file: errors.log
  log_file: logs.log

cache:
  type: redis
  url: localhost:6379
  password: docker
  username: docker

datastore:
  name: showwdb
  username: "postgres"
  password: "postgres"
  host: db
  port: 5432
  ssl: disable
  max_connection: 50

random_user_service:
  client_type: HTTP
  base_url: https://randomuser.me/
  path: "/api"
  timeout: 1000
  headers:
    accept: application/json
